# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class SceneItem(scrapy.Item):
    back = scrapy.Field()
    back_blob = scrapy.Field()
    date = scrapy.Field()
    description = scrapy.Field()
    directors = scrapy.Field()
    director = scrapy.Field()
    duration = scrapy.Field()
    format = scrapy.Field()
    id = scrapy.Field()
    merge_id = scrapy.Field()
    scene_id = scrapy.Field()
    hashes_data = scrapy.Field()
    image = scrapy.Field()
    image_blob = scrapy.Field()
    markers = scrapy.Field()
    network = scrapy.Field()
    parent = scrapy.Field()
    poster = scrapy.Field()
    poster_blob = scrapy.Field()
    performers = scrapy.Field()
    performers_data = scrapy.Field()
    scenes = scrapy.Field()
    movies = scrapy.Field()
    site = scrapy.Field()
    sku = scrapy.Field()
    store = scrapy.Field()
    tags = scrapy.Field()
    title = scrapy.Field()
    file_urls = scrapy.Field()
    trailer = scrapy.Field()
    type = scrapy.Field()
    url = scrapy.Field()
    force_fields = scrapy.Field()
    force_update = scrapy.Field()

class SceneItem2(scrapy.Item):
    back = scrapy.Field()
    back_blob = scrapy.Field()
    date = scrapy.Field()
    description = scrapy.Field()
    director = scrapy.Field()
    directors = scrapy.Field()
    duration = scrapy.Field()
    format = scrapy.Field()
    id = scrapy.Field()
    merge_id = scrapy.Field()
    image = scrapy.Field()
    image_blob = scrapy.Field()
    markers = scrapy.Field()
    network = scrapy.Field()
    parent = scrapy.Field()
    performers = scrapy.Field()
    performers_data = scrapy.Field()
    scenes = scrapy.Field()
    movies = scrapy.Field()
    site = scrapy.Field()
    sku = scrapy.Field()
    store = scrapy.Field()
    tags = scrapy.Field()
    title = scrapy.Field()
    file_urls = scrapy.Field()
    trailer = scrapy.Field()
    type = scrapy.Field()
    url = scrapy.Field()
    phashes = scrapy.Field()
    oshashes = scrapy.Field()

class FileItem(scrapy.Item):
    date = scrapy.Field()
    title = scrapy.Field()
    file_urls = scrapy.Field()
    performers = scrapy.Field()
    site = scrapy.Field()
    network = scrapy.Field()
    file_filename = scrapy.Field()
    file_folder = scrapy.Field()
    dupefile = scrapy.Field()
    resolution = scrapy.Field()
    filename = scrapy.Field()
    url = scrapy.Field()
    id = scrapy.Field()
    existfilelist = scrapy.Field()
    redownload_list = scrapy.Field()
    displayString = scrapy.Field()
    files_store = scrapy.Field()
    meta = scrapy.Field()

class StashItem(scrapy.Item):
    id = scrapy.Field()
    date = scrapy.Field()
    title = scrapy.Field()
    description = scrapy.Field()
    code = scrapy.Field()
    url = scrapy.Field()
    duration = scrapy.Field()
    site = scrapy.Field()
    parent = scrapy.Field()
    performers = scrapy.Field()
    phashes = scrapy.Field()
    oshashes = scrapy.Field()
    tags = scrapy.Field()
    type = scrapy.Field()

class TPDBItem(scrapy.Item):
    back = scrapy.Field()
    back_blob = scrapy.Field()
    date = scrapy.Field()
    description = scrapy.Field()
    director = scrapy.Field()
    directors = scrapy.Field()
    duration = scrapy.Field()
    format = scrapy.Field()
    id = scrapy.Field()
    merge_id = scrapy.Field()
    image = scrapy.Field()
    tpdbimage = scrapy.Field()
    image_blob = scrapy.Field()
    markers = scrapy.Field()
    network = scrapy.Field()
    parent = scrapy.Field()
    performers = scrapy.Field()
    scenes = scrapy.Field()
    movies = scrapy.Field()
    site = scrapy.Field()
    sku = scrapy.Field()
    store = scrapy.Field()
    tags = scrapy.Field()
    title = scrapy.Field()
    file_urls = scrapy.Field()
    trailer = scrapy.Field()
    phashes = scrapy.Field()
    oshashes = scrapy.Field()
    type = scrapy.Field()
    url = scrapy.Field()
    uuid = scrapy.Field()

class MovieItem(scrapy.Item):
    title = scrapy.Field()
    description = scrapy.Field()
    site = scrapy.Field()
    network = scrapy.Field()
    store = scrapy.Field()
    date = scrapy.Field()
    front = scrapy.Field()
    front_blob = scrapy.Field()
    back = scrapy.Field()
    back_blob = scrapy.Field()
    performers = scrapy.Field()
    tags = scrapy.Field()
    url = scrapy.Field()
    markers = scrapy.Field()
    id = scrapy.Field()
    trailer = scrapy.Field()
    studio = scrapy.Field()
    director = scrapy.Field()
    directors = scrapy.Field()
    format = scrapy.Field()
    length = scrapy.Field()
    year = scrapy.Field()
    rating = scrapy.Field()
    sku = scrapy.Field()
    upc = scrapy.Field()
    duration = scrapy.Field()

class PerformerItem(scrapy.Item):
    name = scrapy.Field()
    network = scrapy.Field()
    site = scrapy.Field()
    url = scrapy.Field()
    image = scrapy.Field()
    image_blob = scrapy.Field()
    bio = scrapy.Field()
    gender = scrapy.Field()
    birthday = scrapy.Field()
    astrology = scrapy.Field()
    birthplace = scrapy.Field()
    birthplace_code = scrapy.Field()
    ethnicity = scrapy.Field()
    nationality = scrapy.Field()
    haircolor = scrapy.Field()
    weight = scrapy.Field()
    height = scrapy.Field()
    measurements = scrapy.Field()
    tattoos = scrapy.Field()
    piercings = scrapy.Field()
    cupsize = scrapy.Field()
    fakeboobs = scrapy.Field()
    eyecolor = scrapy.Field()

class PerformerItemExport(scrapy.Item):
    name = scrapy.Field()
    network = scrapy.Field()
    url = scrapy.Field()
    image = scrapy.Field()
    imageFilename = scrapy.Field()
    image_blob = scrapy.Field()
    bio = scrapy.Field()
    gender = scrapy.Field()
    birthday = scrapy.Field()
    astrology = scrapy.Field()
    birthplace = scrapy.Field()
    ethnicity = scrapy.Field()
    nationality = scrapy.Field()
    haircolor = scrapy.Field()
    weight = scrapy.Field()
    height = scrapy.Field()
    measurements = scrapy.Field()
    tattoos = scrapy.Field()
    piercings = scrapy.Field()
    cupsize = scrapy.Field()
    fakeboobs = scrapy.Field()
    eyecolor = scrapy.Field()
